// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Link } from "react-router-dom";

export default function MainNavbar() {
  return (
    <>
      <nav className="navbar navbar-expand-lg bg-white border-bottom">
        <div className="container">
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#mainNav"
            aria-controls="mainNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="mainNav">
            <ul className="navbar-nav mx-auto mb-2 mb-lg-0 gap-lg-4">
              {/* Home Page Link */}
              <li className="nav-item">
                <Link to="/" className="nav-link text-uppercase">
                  Home
                </Link>
              </li>

              {/* About Us Page Link */}
              <li className="nav-item">
                <Link to="/about" className="nav-link text-uppercase">
                  About us
                </Link>
              </li>

              {/* Blog Page Link */}
              <li className="nav-item">
                <Link to="/blog" className="nav-link text-uppercase">
                  Blog
                </Link>
              </li>

              {/* Contact Us Page Link */}
              <li className="nav-item">
                <Link to="/contact" className="nav-link text-uppercase">
                  Contact us
                </Link>
              </li>

              {/* Dropdown */}
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle text-uppercase"
                  href="#pages"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Pages
                </a>
                <ul className="dropdown-menu">
                  <li>
                    <Link to="/about" className="dropdown-item">
                      About us
                    </Link>
                  </li>
                  <li>
                    <a className="dropdown-item" href="#team">
                      Team
                    </a>
                  </li>
                  <li>
                    <Link to="/blog" className="dropdown-item">
                      Blog
                    </Link>
                  </li>
                  <li>
                    <Link to="/contact" className="dropdown-item">
                      Contact us
                    </Link>
                  </li>
                </ul>
              </li>
            </ul>
            <div className="d-flex align-items-center gap-3">
              <a href="#search" className="text-dark">
                <svg width="22" height="22" viewBox="0 0 24 24">
                  <use xlinkHref="#search" />
                </svg>
              </a>
              <button
                className="btn p-0"
                type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#cartCanvas"
                aria-controls="cartCanvas"
                aria-label="Cart"
              >
                <svg width="22" height="22" viewBox="0 0 24 24">
                  <use xlinkHref="#cart" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </nav>
    </>
  );
}
